oliviagreenwell:
    container_name: oliviagreenwell
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
